@echo off
rem Prepares the Boost source tree for building with the MSVC toolset
rem used by this LightGBM build. The integrated build registers the exact
rem compiler and vcvarsall.bat location instead of relying on Boost.Build's
rem Visual Studio discovery. This script therefore:
rem   1. writes user-config.jam registering the exact cl.exe (version tag
rem      supplied by CMake -> matching Boost library names), and
rem   2. writes a setup_msvc.bat wrapper that b2 runs before every tool
rem      invocation to set up the MSVC environment.
rem
rem Usage: prepare_boost.bat BOOST_SOURCE_DIR CL_EXE_PATH VCVARSALL_PATH B2_MSVC_VER VCVARS_VER
setlocal
if "%~1"=="" (echo usage: prepare_boost.bat BOOST_SOURCE_DIR CL_EXE_PATH VCVARSALL_PATH B2_MSVC_VER VCVARS_VER & exit /b 1)
set "BOOST_SRC=%~1"
set "CL_PATH=%~2"
set "VCVARSALL=%~3"
set "B2_MSVC_VER=%~4"
set "VCVARS_VER=%~5"
if not exist "%BOOST_SRC%\bootstrap.bat" (echo bootstrap.bat not found in %BOOST_SRC% & exit /b 1)
if not exist "%CL_PATH%" (echo cl.exe not found: %CL_PATH% & exit /b 1)
if not exist "%VCVARSALL%" (echo vcvarsall.bat not found: %VCVARSALL% & exit /b 1)

rem jam treats backslashes as escape characters: use forward slashes in .jam
set "JAM_BOOST_SRC=%BOOST_SRC:\=/%"
set "JAM_CL_PATH=%CL_PATH:\=/%"

(
echo @echo off
echo rem Generated by LightGBM cmake/prepare_boost.bat - called by Boost.Build to set up the MSVC environment.
echo call "%VCVARSALL%" x64 -vcvars_ver=%VCVARS_VER%
) > "%BOOST_SRC%\setup_msvc.bat"

(
echo # generated by LightGBM cmake/prepare_boost.bat
echo using msvc : %B2_MSVC_VER% : "%JAM_CL_PATH%" : ^<setup^>"%JAM_BOOST_SRC%/setup_msvc.bat" ;
) > "%BOOST_SRC%\user-config.jam"

cd /d "%BOOST_SRC%"
call bootstrap.bat
exit /b %ERRORLEVEL%
